# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

from webapi_tests.telephony.telephony_test import TelephonyTestCommon
from webapi_tests.telephony.test_telephony_incoming import TestTelephonyIncoming
from webapi_tests.telephony.test_telephony_outgoing import TestTelephonyOutgoing
from webapi_tests.telephony.test_telephony_outgoing_hangup_alerting import TestTelephonyOutgoingHangupAlerting
from webapi_tests.telephony.test_telephony_incoming_rejection import TestTelephonyIncomingRejection
from webapi_tests.telephony.test_telephony_incoming_hold_resume import TestTelephonyIncomingHoldResume
from webapi_tests.telephony.test_telephony_incoming_mute import TestTelephonyIncomingMute
from webapi_tests.telephony.test_telephony_incoming_remote_hangup import TestTelephonyIncomingRemoteHangup
from webapi_tests.telephony.test_telephony_outgoing_remote_hangup import TestTelephonyOutgoingRemoteHangup
from webapi_tests.telephony.test_telephony_incoming_multiple import TestTelephonyIncomingMultiple
from webapi_tests.telephony.test_telephony_outgoing_speaker import TestTelephonyOutgoingSpeaker
from webapi_tests.telephony.test_telephony_incoming_hold_outgoing import TestTelephonyIncomingHoldOutgoing
from webapi_tests.telephony.test_telephony_outgoing_incoming import TestTelephonyOutgoingIncoming
from webapi_tests.telephony.test_telephony_incoming_sendtone import TestTelephonyIncomingSendtone
from webapi_tests.telephony.test_telephony_outgoing_busy import TestTelephonyOutgoingBusy
